name: XcodeBuildTest

on:
  push:
    branches:
      - main

jobs:
  hello-world: # job id
    name: select os
    runs-on: macos-13
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: xcode build
        run: xcodebuild 
              -project AppGithubActions01.xcodeproj
              -scheme AppGithubActions01
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=16.1'
              build
