name: XcodeBuildTest

on:
  push:
    branches:
      - main

jobs:
  hello-world: # job id
    name: select os
    runs-on: macos-13
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: xcode clean build
        run: xcodebuild clean -project AppGithubActions01.xcodeproj
      - name: xcode build
        run: |
          set -o pipefail && xcodebuild -project AppGithubActions01.xcodeproj \
                     -scheme AppGithubActions01 \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' \
                     -configuration Debug build

