name: XcodeBuildTest

on:
  push:
    branches:
      - main

jobs:
  hello-world: # job id
    name: select os
    runs-on: macos-13
    steps:
      - name: check out
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
